version: '3'

networks:
  secure_net:
   driver: overlay
   attachable: true

services:
  redis-service:
   image: redis:latest
   volumes:
    - ./redis_data:/data
   environment:
     REDIS_ARGS: "--save 10 1"
   networks:
    - secure_net

  flask-app:
    build: .
    ports:
     - 8000:8000
    environment:
      FLASK_ENV: development
    networks:
    - secure_net
